AWSTemplateFormatVersion: 2010-09-09
Description: Template para el despliegue de las instancias EC2 para Continuidad

Parameters:

  pInstanceTypeEc2:
    Description: EC2 instance type
    Type: String

  pInstanceAMI:
    Description: codigo de la ami
    Type: String
    
  pPrivateSubnet1:
    Description: ID of private subnet 1.
    Type: String
  
  pPrivateSubnet2:
    Description: ID of private subnet 2.
    Type: String

  #tags obligatorios

  pEnvironment:
    Description: Ambiente de despliegue
    Type: String

  pProjectname:
    Description: Nombre del proyecto
    Type: String

  pApplicationcode:
    Description: Codigo de la aplicacion.
    Type: String
  
  pCostCenter:
    Description: centro de costos
    Type: String
  
  pPmo:
    Description: pmo
    Type: String

  pBusinessService:
    Description: componente mayor
    Type: String

Resources:
  # Instancias EC2 para Continuidad
  rEC2Continuidad1:
    Type: AWS::EC2::Instance
    Properties:
      DisableApiTermination: True
      IamInstanceProfile:
        Ref: rEC2InstanceProfile
      ImageId:
        Ref: pInstanceAMI
      InstanceType:
        Ref: pInstanceTypeEc2
      SubnetId: 
        Ref: pPrivateSubnet1   
      SecurityGroupIds: 
        - !ImportValue SgContinuidadVar
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref pApplicationcode, !Ref pProjectname, !Ref pEnvironment, ec2, 1]]
        
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo su
          systemctl restart amazon-ssm-agent
          yum -y update 
          yum -y install httpd
          systemctl start httpd.service
          systemctl enable httpd.service
          EC2_AVAIL_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
          echo "<h1>Hello World</h1><p>Hello World from instance $(hostname -f) in AZ $EC2_AVAIL_ZONE</p>" > /var/www/html/index.html
          chmod 755 /var/www/html/index.html

  rEC2Continuidad2:
    Type: AWS::EC2::Instance
    Properties:
      DisableApiTermination: True
      IamInstanceProfile:
        Ref: rEC2InstanceProfile
      ImageId:
        Ref: pInstanceAMI
      InstanceType:
        Ref: pInstanceTypeEc2
      SubnetId: 
        Ref: pPrivateSubnet2
      SecurityGroupIds: 
        - !ImportValue SgContinuidadVar
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref pApplicationcode, !Ref pProjectname, !Ref pEnvironment, ec2, 2]]

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo su
          systemctl restart amazon-ssm-agent
          yum -y update 
          yum -y install httpd
          systemctl start httpd.service
          systemctl enable httpd.service
          EC2_AVAIL_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
          echo "<h1>Hello World</h1><p>Hello World from instance $(hostname -f) in AZ $EC2_AVAIL_ZONE</p>" > /var/www/html/index.html
          chmod 755 /var/www/html/index.html

  rEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !ImportValue RoleContinuidadVar
